### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by bobmulder**
I am not english, but I think it should be 'turns' (he, she, it rule ;))

### CODE REVIEW

**Comment by mnapoli** [comment]
Thanks!

**Comment by bobmulder** [comment]
Travis fails? :(

**Comment by wysow** [comment]
@bobmulder Nope, @mnapoli is just too fast when merging typos ;)

**Comment by mnapoli** [comment]
:+1: quick merge to sweep the typo under the rug :p

**Comment by bobmulder** [comment]
Just curious, I see that the docs are not generated automatically?

**Comment by mnapoli** [comment]
All good now: http://couscous.io/ (I wasn't able to update them earlier today)

Indeed they are not generated automatically because we embed `couscous.phar` on the website, so we don't want to build it everytime a commit happens on `master` else we would be deploying dev versions. We would need a more clever release script running on Travis, but it's probably not the simplest to write and nobody has done it yet. I'm fine releasing/updating the website manually for now.

**Pull request merged**
