### PR TITLE
issue 211: keep documentation visible for wide viewports

### PR DESCRIPTION
**Pull request by nklatt**

### CODE REVIEW

**Comment by mnapoli** [comment]
This is what I get with your patch:

capture d ecran 2018-05-22 a 14 20 34

Can you show us what the pull request is fixing and what the problem is with screenshots please?

Thanks

**Comment by nklatt** [comment]
I'm sorry, the issue I'm seeing on the live site is that at around 1280px wide, some of the `section.documentation` content is inaccessible because it is off the right side of the viewport. Logically, given the `nav#sidebar` is `.col-lg-2` and `section.documentation` is `.col-lg-10`, it seems reasonable you'd want the `section.documentation` offset to match the width of `nav#sidebar`. It also seems logical that `.col-lg-offset-3` + `.col-lg-10` would total 13 which would be more than 12. Apparently I'm missing something else about how the styling is working, however. I'm going to go ahead and just leave this and you can look further into it or not at your discretion.

**Comment by mnapoli** [comment]
Right I managed to reproduce:

capture d ecran 2018-05-22 a 22 36 46

You are correct that the Bootstrap columns are messed up. I think I changed the padding/margins of the columns, which is a no-no but I did it anyway 🤔 (can I argue that it was a long time ago and that I know better now? ^^) It will be a bit more work to make it right unfortunately :/

**Comment by mnapoli** [comment]
Oh nice I didn't think of that! Thanks!

**Comment by cyberbit** [comment]
Don't mind me, I'm just a fly on the wall, but I think that's cheating 😜

**Comment by mnapoli** [comment]
Hehe 🙈

**Pull request merged**
