### PR TITLE
Updating dependencies

### PR DESCRIPTION
**Pull request by wysow**
This is to fix a problem when instantiating ParsedownExtra class which was throwing an error for an `array_unshift` bad call...

### CODE REVIEW

**Comment by mnapoli** [comment]
:+1:

**Comment by wysow** [comment]
I'm facing another problem when trying to launch preview command, working on a fix that I will add on this PR

**Comment by mnapoli** [comment]
Feel free to merge when done, this is trivial change.

**Comment by wysow** [comment]
OK my other problem is now fixed on the related dependency so I'm merging this...

**Pull request merged**
