### PR TITLE
[#242] use HTTPS

### PR DESCRIPTION
**Pull request by webmaster777**
see #242

### CODE REVIEW

**Comment by mnapoli** [comment]
Thank you, but it looks like you did a full search+replace. Some links are broken, I cannot merge this blindly.

**Comment by webmaster777** [comment]
I've tried to check all the links I've replaced to see if they work. Do you have an example of a broken link?

**Comment by webmaster777** [comment]
Ah i see. I Think I found where I started speed-reviewing my changes: e.g. `website/home-portfolio.twig`

**Comment by mnapoli** [comment]
Let's move forward, thanks for the PR!

**Pull request merged**
