### PR TITLE
Add Ovac Couscous template

### PR DESCRIPTION
**Pull request by ovac**

### CODE REVIEW

**Comment by mnapoli** [comment]
Awesome thanks!

**Comment by ovac** [comment]
@mnapoli The pleasure is all mine! I'd love to do so much more.. I'm in love with couscous!

**Comment by ovac** [comment]
@mnapoli, I have a question though. Do I also have to send a pull request of the generated html for the gh-pages or?

**Comment by mnapoli** [comment]
@ovac I've redeployed the website, it should all be good now!

**Pull request merged**
