### PR TITLE
WIP Added php7 to travis and make use of docker

### PR DESCRIPTION
**Pull request by fonsecas72**
I will try to fix the php7 build.

### CODE REVIEW

**Comment by fonsecas72** [comment]
This is failing due to erusev/parsedown. While master is compatible with PHP7, last release it's not.

**Comment by fonsecas72** [comment]
mnapoli/FrontYAML will have to bump erusev/parsedown to last version (be it master or a new version that's yet not been release)
And then we will have to bump mnapoli/FrontYAML both there and here.

**Comment by mnapoli** [comment]
Wow we found a library not PHP7 compatible! Didn't think I'd see that ;)

We'll have to wait for a new stable release of Parsedown though, we can't require master. Thanks for the PR, let's keep it open.

**Comment by fonsecas72** [comment]
> Wow we found a library not PHP7 compatible! Didn't think I'd see that ;)

Why the Irony ? ;)

> We'll have to wait for a new stable release

Sure, I think they will release one in a few days.

**Comment by mnapoli** [comment]
I don't know I expected only old legacy applications to break, but maybe not :)

**Comment by fonsecas72** [comment]
There are some BC breaks already: https://github.com/php/php-src/blob/master/UPGRADING.
But yeah, mostly edge cases or misbehaviors for now :)

**Comment by mmoreram** [comment]
@fonsecas72 PHP7 is already added in #100

**Comment by fonsecas72** [comment]
@mmoreram that means that erusev/parsedown tagged a new release. Nice.
btw you can also add the ```sudo: false``` to travis. It will make it a little faster.

**Pull request closed without merging**
