### PR TITLE
Improve Markdown links parser

### LINKED ISSUE #53: Convert Markdown files and links to lower-case
On Couscous and other projects there is a `CHANGELOG.md` or `CONTRIBUTING.md`. When we want to link to it in the website, it gives this ugly URL: http://php-di.org/CONTRIBUTING.html

it would be nice to turn those links and HTML files in lower case.

### PR DESCRIPTION
**Pull request by henriquemoody**
- Rename upper case links to lower case
- Replace "README.md" files to "index.html" in Markdown files
- Replace uppercase links to lower case in Markdown files
- Update FAQ with the new information about links
- Fix broken link to changelog file

Fix #53.

### CODE REVIEW

**Comment by wysow** [comment]
@henriquemoody Thanks for this, seems good for me ;)

**Comment by henriquemoody** [comment]
I just update the docs.

**Comment by mnapoli** [comment]
Awesome!

Code + tests + documentation === :tada:

**Comment by henriquemoody** [comment]
You're welcome! :smile:

**Pull request merged**
