### PR TITLE
Support --version

### LINKED ISSUE #243: Couscous version output
When I run
> php bin/couscous.phar --version

 I get
> Console Tool

No version output.

### PR DESCRIPTION
**Pull request by Nyholm**
This will fix #243

I made the assumption that this project always will be deployed with Travis.

### CODE REVIEW

**Comment by Nyholm** [comment]
Hm.. It seams like travis is not running.

**Comment by Nyholm** [comment]
So Travis is runnig. But the Github<->Travis integration should be fixed. 

Also, Travis does not have permission to publish phars: 
https://travis-ci.org/github/CouscousPHP/Couscous/jobs/600093417

**Comment by Nyholm** [comment]
This PR is ready for review

**Comment by mnapoli** [comment]
Thanks!

**Pull request merged**
