### PR TITLE
Add a configuration step to check that the default timezone is set

### PR DESCRIPTION
**Pull request by mpodolian**
This fixes  issue #119.
No unit test, as ini_set / ini_get functions are hard to mock.

### CODE REVIEW

**Comment by mnapoli** [comment]
Hi, thank you for contributing!

This is a very clean PR but I think it might be better to put the `date_default_timezone_set()` call directly in [`bin/couscous`](https://github.com/CouscousPHP/Couscous/blob/master/bin/couscous). The reason is that it's just a simple system call (so it's fine if it's hardcoded somewhere, as you said we don't test it), and also (mainly) because there might be some code executed before this step that might raise the issue.

**Comment by mpodolian** [comment]
Agreed, setting it up in the Step felt weird, as it is not project related.

**Comment by mnapoli** [comment]
Thanks!

**Comment by mnapoli** [comment]
This has been released as [1.3.2](https://github.com/CouscousPHP/Couscous/releases/tag/1.3.2) thank you!

**Pull request merged**
