### PR TITLE
Github Action

### PR DESCRIPTION
**Pull request by BilelJegham**
Hi, 
I just made an action for Github : https://github.com/BilelJegham/action-couscous 
I add to the doc the github workflow.

 Do you want to owe the repo on Couscous org ?

### CODE REVIEW

**Comment by mnapoli** [comment]
Thanks that's great!

Yes we could definitely move this repository to the Couscous organization, but would you be OK to be a maintainer of that repo?

**Comment by BilelJegham** [comment]
Great, Ok!

Then we can publish the action on the Github marketspace.

Le mar. 10 mars 2020 à 13:41, Matthieu Napoli <notifications@github.com> a
écrit :

**Comment by mnapoli** [comment]
Yep! You will need to move the repository to the @CouscousPHP organization to move forward.

**Comment by BilelJegham** [comment]
image
I don't have the permission to "Transfer ownership".

**Comment by mnapoli** [comment]
Sorry for the delay, I have created https://github.com/CouscousPHP/GitHub-Action and added you as maintainer. You can either push all your code as 1 commit, or try to preserve the history of your repository by pushing the existing commits.

**Comment by BilelJegham** [comment]
Great, I do it as soon as possible (this week)

**Comment by BilelJegham** [comment]
I push the code, but can you change the default branch to `master` on Github-Action Repo. I don't have permission.

**Comment by BilelJegham** [comment]
Maybe can you give me ownership of the Github Action repo ?

**Comment by mnapoli** [comment]
Sorry for the delay! I have changed the default branch. You should have "Maintain" permissions, but indeed that setting wasn't available to you. Let me know if you need anything else, I'll try to keep up more closely.

Is this PR ready to merge for you? (the build is failing on master, not related to your PR)

**Comment by BilelJegham** [comment]
Yes, PR ready and action publish on Github Marketplace : https://github.com/marketplace/actions/couscous-generate

**Comment by mnapoli** [comment]
Awesome thanks!

**Pull request merged**
